# configuration for "master" branch
-
  branches:
    only:
      - master
  configuration: Release
  platform: Any CPU
  skip_tags: true
  image: Visual Studio 2015
  version: 5.0.{build}
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true
  environment:
    COVERALLS_REPO_TOKEN:
      secure: UFzWya6z1lSVM9ns9TIhin52+NW1NkH6lov5kRm91AWnK83utbXWDlUwtnXeeshJ
  build:
    parallel: true
    project: CakeMail.RestClient.sln
    publish_nuget: true
    verbosity: minimal
  before_build:
    - nuget restore
  test_script:
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"vstest.console.exe" -targetargs:"/logger:Appveyor ""CakeMail.RestClient.UnitTests\bin\%configuration%\CakeMail.RestClient.UnitTests.dll""" -filter:"+[CakeMail.RestClient]* -[CakeMail.RestClient]CakeMail.RestClient.Models.* -[CakeMail.RestClient]CakeMail.RestClient.Properties.*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -hideskipped:"All" -output:coverage.xml
  after_test: 
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  notifications:
    - provider: Email
      to:
      - desautelsj@hotmail.com
      subject: CakeMail.RestClient Build
      on_build_success: true
      on_build_failure: true
      on_build_status_changed: false
  deploy:
    provider: NuGet
    api_key:
      secure: TtNPR7FUOtryJtreq842P15PwOPdYKkGFjk3F7yfWCAjhMJx8l8Vx6b0FfKq7E+o
    artifact: /.*\.nupkg/



# "fall back" configuration for all other branches
# no "branches" section defined
-
  configuration: Release
  platform: Any CPU
  skip_tags: true
  image: Visual Studio 2015
  version: 5.0.{build}-pre
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  nuget:
    account_feed: true
    project_feed: true
    disable_publish_on_pr: true
  environment:
    COVERALLS_REPO_TOKEN:
      secure: UFzWya6z1lSVM9ns9TIhin52+NW1NkH6lov5kRm91AWnK83utbXWDlUwtnXeeshJ
  build:
    parallel: true
    project: CakeMail.RestClient.sln
    publish_nuget: true
    verbosity: minimal
  before_build:
    - nuget restore
  test_script:
    - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"vstest.console.exe" -targetargs:"/logger:Appveyor ""CakeMail.RestClient.UnitTests\bin\%configuration%\CakeMail.RestClient.UnitTests.dll""" -filter:"+[CakeMail.RestClient]* -[CakeMail.RestClient]CakeMail.RestClient.Models.* -[CakeMail.RestClient]CakeMail.RestClient.Properties.*" -excludebyattribute:"*.ExcludeFromCodeCoverage*" -hideskipped:"All" -output:coverage.xml
  after_test: 
    - packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml
  notifications:
    - provider: Email
      to:
      - desautelsj@hotmail.com
      subject: CakeMail.RestClient Build
      on_build_success: false
      on_build_failure: false
      on_build_status_changed: true
