# Before Build
init:
  - git config --global core.autocrlf true

# Build script
build_script:
  - ps: .\build.ps1 -Target "AppVeyor"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - master
    - /release/.*/
    - /hotfix/.*/

# Build cache
cache:
  - '%USERPROFILE%\.nuget\packages -> Source\**\project.json'  # Note the use of single quotes around the entire line, when environment variables are used.
  - tools -> build.cake, tools\packages.config

# Environment configuration
image: Visual Studio 2017
