# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 2.0.{build}-{branch}

# Do not build on tags (GitHub only)
skip_tags: true


#---------------------------------#
#    environment configuration    #
#---------------------------------#
 
# Operating system (build VM template)
os: Windows Server 2012 R2

# Automatically register private account and/or project AppVeyor NuGet feeds.
nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true     # disable publishing of .nupkg artifacts to
                                  # account/project feeds for pull request builds

environment:
  COVERALLS_REPO_TOKEN:
    secure: UFzWya6z1lSVM9ns9TIhin52+NW1NkH6lov5kRm91AWnK83utbXWDlUwtnXeeshJ


#---------------------------------#
#       build configuration       #
#---------------------------------#
 
# build platform, i.e. x86, x64, Any CPU.
platform: Any CPU
  
# build Configuration, i.e. Debug, Release, etc.
configuration: Release

build:
  parallel: true                  # enable MSBuild parallel builds
  project: CakeMail.RestClient.sln # path to Visual Studio solution or project
  publish_nuget: true             # package projects with .nuspec files and push to artifacts
  verbosity: minimal              # MSBuild verbosity level (quiet|minimal|normal|detailed)


#---------------------------------#
#             Scripts             #
#---------------------------------#
 
before_build:
- nuget restore

after_test: 
    - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[CakeMail.RestClient]* -[CakeMail.RestClient]CakeMail.RestClient.Models.* -[CakeMail.RestClient]CakeMail.RestClient.Properties.*" -target:"vstest.console.exe" -targetargs:"""CakeMail.RestClient.UnitTests\bin\%configuration%\CakeMail.RestClient.UnitTests.dll""" -output:coverage.xml
    - cat coverage.xml
    - bash <(curl -s https://codecov.io/bash)


#---------------------------------#
#          notifications          #
#---------------------------------#

notifications:
- provider: Email
  to:
  - desautelsj@hotmail.com
  subject: CakeMail.RestClient Build
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true
